{{- if .Values.openshiftGitops.initialApps }}
{{- range $app := .Values.openshiftGitops.initialApps }}
{{- range $ns := $.Values.openshiftGitops.namespaces }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  destination:
    namespace: {{ $ns }}
    server: 'https://kubernetes.default.svc'
  source:
    path: {{ $app.path }}
    repoURL: {{ $app.repoURL }}
    targetRevision: {{ $app.targetRevision }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
{{- end }}
{{- end }}