{{- if .Values.openshiftGitops.enabled }}
{{- if .Values.openshiftGitops.namespaces }}
---
apiVersion: v1
kind: Pod
metadata:
  name: cluster-check 
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  namespace: {{ .Values.openshiftGitops.namespaces | first }}
spec:
  containers:
  - name: crd-check 
    image: {{ .Values.cleanupContainerImage }}
    resources:
      requests:
        memory: {{ .Values.resources.requests.memory }}
        cpu: {{ .Values.resources.requests.cpu }}
      limits:
        memory: {{ .Values.resources.limits.memory }}
        cpu: {{ .Values.resources.limits.cpu }}
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'while [ true ]; do oc get crd argocds.argoproj.io applications.argoproj.io appprojects.argoproj.io; if [ $? -eq 0 ]; then break; fi ; sleep 5s; done']
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  serviceAccount: default
  serviceAccountName: default
{{- end }}
{{- end }}