openshiftPipelines:
  subscription:
    namespace: operators
    name: openshift-pipelines-operator-rh
    spec:
      channel: alpha
      installPlanApproval: Automatic
      name: tektoncd-operator
      source: operatorhubio-catalog
      sourceNamespace: olm

openshiftGitops:
  name: argocd
  namespaces:
    - olm
  subscription:
    namespace: operators
    spec:
      channel: alpha
      installPlanApproval: Automatic
      name: argocd-operator
      source: operatorhubio-catalog
      sourceNamespace: olm

cleanupContainerImage: bitnami/kubectl:latest
